### ISSUE TITLE
Fuzz test `calculate_*` trades against solidity

### ISSUE THREAD

**Issue by slundqui** [delvtech/hyperdrive#937] opened 2024-04-03 22:02 UTC
There are limited tests for rust `calculate_*` functions against what's implemented in solidity:

- Open long/short doesn't fuzz against solidity.
- Close long/short only fuzzes the underlying `calculate_close_long_flat_plus_curve` and `calculate_close_short_flat_plus_curve` against the `calculate_close_*` from hyperdrive math. However, these functions do not take fees or negative interest checks into account (both on the solidity and rust side).

Ideally, we would fuzz these trades against the public interface of hyperdrive.

**Comment by dpaiton** [comment] 2024-05-01 20:38
Duplicate of #861; closing

**Closed by dpaiton** 2024-05-01 20:38 UTC
Labels: rust-sdk
